# Generated by Django 3.2.16 on 2022-11-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('posting_service', models.CharField(max_length=50)),
                ('received', models.DateTimeField(verbose_name='Date office received')),
            ],
        ),
    ]
