# Generated by Django 3.2.16 on 2022-11-23 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_resident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='address',
        ),
    ]
